In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from apyori import apriori

In [7]:
df = pd.read_csv('TV Shows - Association Rule Learning.csv', header = None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Cobra Kai,Lupin,12 Monkeys,Sherlock,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lost,Jack Ryan,The Flash,Game of thrones,House of Cards,12 Monkeys,Vikings,Fringe,The Mentalist,The Alienist,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sex Education,Dr. House,Kingdom,The Walking Dead,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ozark,Sex Education,Constantine,Preacher,Vikings,The Tick,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Naruto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
transactions = []
for i in range(0, 9689):
    transactions.append([str(df.values[i,j]) for j in range(0, 31)])

In [80]:
rules = apriori(transactions = transactions, min_support = 0.002, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

In [81]:
results = list(rules)
results

[RelationRecord(items=frozenset({'12 Monkeys', 'Game of thrones'}), support=0.0038187635462896066, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'12 Monkeys'}), confidence=0.22023809523809523, lift=3.756843142186452)]),
 RelationRecord(items=frozenset({'Alice in Borderland', 'Daredevil'}), support=0.007121477964702239, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Alice in Borderland'}), items_add=frozenset({'Daredevil'}), confidence=0.2875, lift=3.0610851648351645)]),
 RelationRecord(items=frozenset({'Archer', 'Prison Break'}), support=0.0025802456393848694, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Prison Break'}), items_add=frozenset({'Archer'}), confidence=0.25252525252525254, lift=4.369137806637807)]),
 RelationRecord(items=frozenset({'The Wire', 'Arrow'}), support=0.005779750232222107, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Arrow'}), items_add=frozenset({'The Wire'}), confidence=0.22134387351778653, lift=3.3667202362854534)]),
 RelationRecord(items=frozenset({'The Wire', 'Breaking Bad'}), support=0.004231602848591186, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Breaking Bad'}), items_add=frozenset({'The Wire'}), confidence=0.25308641975308643, lift=3.849535825726302)]),
 RelationRecord(items=frozenset({'The 100', 'Dark'}), support=0.004644442150892765, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The 100'}), items_add=frozenset({'Dark'}), confidence=0.41666666666666663, lift=4.677964465044418)]),
 RelationRecord(items=frozenset({'Game of thrones', 'Family Guy'}), support=0.004025183197440396, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'Family Guy'}), confidence=0.23214285714285715, lift=3.245645227788085)]),
 RelationRecord(items=frozenset({'Punisher', 'Family Guy'}), support=0.004644442150892765, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Punisher'}), items_add=frozenset({'Family Guy'}), confidence=0.26011560693641617, lift=3.6367389835597925)]),
 RelationRecord(items=frozenset({'Family Guy', 'Rick And Morty'}), support=0.009185674476210135, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Rick And Morty'}), items_add=frozenset({'Family Guy'}), confidence=0.2763975155279503, lift=3.864380271212569)]),
 RelationRecord(items=frozenset({'Lost', 'Fringe'}), support=0.0030962947672618433, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Fringe'}), items_add=frozenset({'Lost'}), confidence=0.379746835443038, lift=11.391229376494103)]),
 RelationRecord(items=frozenset({'Game of thrones', 'Vikings'}), support=0.0048508618020435545, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'Vikings'}), confidence=0.27976190476190477, lift=8.289336682685308)]),
 RelationRecord(items=frozenset({'Hanna', 'Sopranos'}), support=0.0025802456393848694, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Sopranos'}), items_add=frozenset({'Hanna'}), confidence=0.2136752136752137, lift=3.613087513611074)]),
 RelationRecord(items=frozenset({'The Blacklist', 'Homeland'}), support=0.002270616162658685, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Homeland'}), items_add=frozenset({'The Blacklist'}), confidence=0.3235294117647059, lift=3.0853114867994447)]),
 RelationRecord(items=frozenset({'Suits', 'How to get away with murder'}), support=0.002270616162658685, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Suits'}), items_add=frozenset({'How to get away with murder'}), confidence=0.3098591549295775, lift=8.136112065346007)]),
 RelationRecord(items=frozenset({'Into the night', 'The Blacklist'}), support=0.0026834554649602643, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Into the night'}), items_add=frozenset({'The Blacklist'}), confidence=0.325, lift=3.09933562992126)]),
 RelationRecord(items=frozenset({'Person of Interest', 'Mr. Robot'}), support=0.00691505831355145, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Person of Interest'}), items_add=frozenset({'Mr. Robot'}), confidence=0.4294871794871795, lift=3.925755926463474)]),
 RelationRecord(items=frozenset({'Queen of the South', 'Mr. Robot'}), support=0.017339250696666322, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Queen of the South'}), items_add=frozenset({'Mr. Robot'}), confidence=0.32941176470588235, lift=3.011009988901221)])]

In [83]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['FILM_1', 'FILM_2', 'Support', 'Confidence', 'Lift'])

In [84]:
clean = resultsinDataFrame.nlargest(n = 15, columns = 'Support')
clean.sort_values(by=['Support','Confidence','Lift'],ascending=False)

                 FILM_1         FILM_2   Support  Confidence       Lift
16   Queen of the South      Mr. Robot  0.017339    0.329412   3.011010
8        Rick And Morty     Family Guy  0.009186    0.276398   3.864380
1   Alice in Borderland      Daredevil  0.007121    0.287500   3.061085
15   Person of Interest      Mr. Robot  0.006915    0.429487   3.925756
3                 Arrow       The Wire  0.005780    0.221344   3.366720
10      Game of thrones        Vikings  0.004851    0.279762   8.289337
5               The 100           Dark  0.004644    0.416667   4.677964
7              Punisher     Family Guy  0.004644    0.260116   3.636739
4          Breaking Bad       The Wire  0.004232    0.253086   3.849536
6       Game of thrones     Family Guy  0.004025    0.232143   3.245645
0       Game of thrones     12 Monkeys  0.003819    0.220238   3.756843
9                Fringe           Lost  0.003096    0.379747  11.391229
14       Into the night  The Blacklist  0.002683    0.325000   3.099336
2          Prison Break         Archer  0.002580    0.252525   4.369138
11             Sopranos          Hanna  0.002580    0.213675   3.613088